#spring.application.name=JwtSecurityProject

spring:
  application:
    name: JwtSecurityProject
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: ${db_url}
    password: ${db_password}
    username: ${db_user}

server:
  error:
    include-message: always
